version: "3.9"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_HOST_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks:
      - backend

  backend:
    depends_on:
      - mongodb
    image: $AWS_ECR_BACKEND
    restart: unless-stopped
    ports:
      - $NODE_HOST_PORT:$NODE_DOCKER_PORT
    env_file: ./backend.env
    networks:
      - backend
      - app-network

  frontend:
    depends_on:
      - backend
    image: $AWS_ECR_FRONTEND
    restart: unless-stopped
    environment:
      - ADMIN_PERMISSION_KEY=$ADMIN_PERMISSION_KEY
    ports:
      - $REACT_HOST_PORT:$REACT_DOCKER_PORT
    networks:
      - app-network
  nginx:
    depends_on:
      - backend
      - frontend
    image: $AWS_ECR_NGINX
    restart: unless-stopped
    ports:
      - $NGINX_HOST_PORT:$NGINX_DOCKER_PORT
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
  backend:
