version: "3.9"

services:
  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8081:8081
    networks:
      - backend

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_HOST_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks:
      - backend

  backend:
    depends_on:
      - mongodb
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_HOST_PORT:$NODE_DOCKER_PORT
    environment:
      - PORT=$NODE_HOST_PORT
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - JWT_SECRET=$JWT_SECRET
    networks:
      - backend
      - app-network

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
    ports:
      - $REACT_HOST_PORT:$REACT_DOCKER_PORT
    networks:
      - app-network
  nginx:
    depends_on:
      - backend
      - frontend
    build:
      context: ./nginx
    ports:
      - $NGINX_HOST_PORT:$NGINX_DOCKER_PORT
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
  backend:
